project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy:
files:
  - source: /apps/client/src/locales/en-US/messages.po
    translation: /apps/client/src/locales/%locale%/messages.po
