name: 🐞 Bug Report
description: File a bug report for the Reactive Resume self-hosted fork
title: "[Bug] "
labels: [bug, needs triage, v1]
assignees: "lazy-media"

body:
  - type: checkboxes
    attributes:
      label: Verification Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I've searched existing issues and confirmed this is new
        - label: I've tested on multiple browsers/device
        - label: I've attempted troubleshooting (cache clearing, etc.)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: What is happening?
      placeholder: "Example: PDF export fails with 'Network Error'"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Example: PDF should export successfully"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to recreate the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Browser(s) Affected
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Brave
        - Other (specify below)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Template Used (if applicable)
      options:
        - Azurill
        - Bronzor
        - Chikorita
        - Ditto
        - Gengar
        - (other templates...)
        - Not template-specific
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        System info, screenshots, or error logs
        (Drag files here to attach)
    validations:
      required: false
