name: 🐞 Bug Report
description: File a bug report for the Reactive Resume self-hosted fork
title: "[Bug] "
labels: ["bug", "self-hosted", "needs triage"]
assignees: "lazy-media"

body:
  - type: checkboxes
    attributes:
      label: Verification Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I've searched existing issues and confirmed this is new
          required: true
        - label: I've tested on multiple browsers/devices
          required: true
        - label: I've attempted troubleshooting (cache clearing, etc.)
          required: true
        - label: This occurs in the self-hosted version (not cloud)
          required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: What is happening?
      placeholder: "Example: PDF export fails with 'Network Error'"
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Example: PDF should export successfully"
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to recreate the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll to '...'
        4. See error
      required: true

  - type: dropdown
    attributes:
      label: Browser(s) Affected
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Brave
        - Other (specify below)
      required: true

  - type: dropdown
    attributes:
      label: Template Used (if applicable)
      options:
        - Azurill
        - Bronzor
        - Chikorita
        - Ditto
        - Gengar
        - (other templates...)
        - Not template-specific
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        System info, screenshots, or error logs
        (Drag files here to attach)
      required: false