blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: ./bug-report.yml
    about: Submit Bug Reports here
  - name: Feature Requests
    url: ./feature-request.yml
    about: Submit Feature Requests here
  - name: Documentation Update
    url: ./documentation-update.yml
    about: Request updates or improvements to the documentation.
#  - name: GitHub Community Support
#    url: https://github.com/orgs/community/discussions
#    about: Please ask and answer questions here.
#  - name: GitHub Security Bug Bounty
#    url: https://bounty.github.com/
#    about: Please report security vulnerabilities here.
