name: "📚 Documentation Update"
description: "Request an update or improvement to the documentation."
title: "[Docs] "
labels: ["documentation", "v1", "needs triage"]
assignees: "lazy-media"
projects: "Reactive Resume"
body:
  - type: markdown
    attributes:
      value: |
        **For best results on what you want published to the site, please send your content in Markdown Format.**
  - type: dropdown
    id: doc-section
    attributes:
      label: "Which section of the documentation needs to be updated?"
      description: "Select the main area or section that your update relates to."
      options:
        - "Overview: Information"
        - "Overview: Features"
        - "Engineering: Mission"
        - "Engineering: Tech Stack"
        - "Engineering: How it Works Frontend"
        - "Engineering: How it Works Backend"
        - "Contributing: Sponsor Through GitHub"
        - "Contributing: Sponsor Through Open Collective"
        - "Contributing: Translations"
        - "Product Guides: Setting Up Your Account"
        - "Product Guides: Updating Your Profile"
        - "Product Guides: Updating Your Password"
        - "Product Guides: Setting Up Two-Factor Authentication"
        - "Product Guides: Enabling OpenAI Integration"
        - "Product Guides: Enabling OpenWebUI Integration"
        - "Product Guides: Translate Your Resume with ChatGPT"
        - "Product Guides: Use ChatGPT to rewrite your resume"
        - "Product Guides: Exporting Your Resume as JSON"
        - "Product Guides: Exporting Your Resume as PDF"
        - "Product Guides: Making Your Resume Publicly Available"
        - "Product Guides: Importing your data from LinkedIn"
        - "Product Guides: Creating Multi Page Resumes"
        - "Product Guides: Change the number of columns per section"
        - "Product Guides: Custom CSS Styling"
        - "Self Hosting Guides: Simple"
        - "Self Hosting Guides: NGINX"
        - "Meta: License"
        - "Meta: Privacy Policy"
        - "Meta: Terms of Service"
    validations:
      required: true

  - type: dropdown
    id: change-type
    attributes:
      label: "Type of documentation update"
      description: "Choose the type of update you are requesting."
      options:
        - "Correction (fix typo, error, outdated content)"
        - "Clarification (improve wording or explanation)"
        - "Addition (add new content or example)"
        - "Removal (delete incorrect or obsolete content)"
        - "Reorganization (move or restructure docs)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Describe the documentation update"
      description: "Provide a clear and detailed description of what needs to be changed, added, or improved. Include specific file names or URLs if known."
      placeholder: "Example: The configuration section is missing an explanation for the 'theme' option in config.yml."
    validations:
      required: true

  - type: textarea
    id: replacement
    attributes:
      label: "How would you like the documentation to read instead?"
      description: "Please provide the exact text you'd like to update on the Docs Site, ensuring it is clear, concise, and thoroughly detailed. For optimal compatibility, submit this content in Markdown format."
      placeholder: "Please input your extremely detailed documentation replacement here. Preferrebly in Markdown Format."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional context or screenshots (optional)"
      description: "Add any other context, screenshots, or relevant details that might help us understand your request."

  - type: checkboxes
    id: self-check
    attributes:
      label: "Self-check"
      description: "Please confirm the following before submitting:"
      options:
        - label: "I have searched existing issues to avoid duplicates."
          required: true
        - label: "The requested change is relevant to the Reactive-Resume-Docs repository."
          required: true
