name: ✨ Feature Request
description: Suggest an enhancement for the self-hosted fork
title: "[Feature] "
labels: ["enhancement", "self-hosted", "needs triage"]
assignees: "lazy-media"

body:
  - type: checkboxes
    attributes:
      label: Verification Checklist
      options:
        - label: I've searched existing issues and confirmed this is new
        - label: This benefits multiple users (not just my specific use case)
        - label: This is for the self-hosted version (not cloud)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Feature Description
      description: What problem does this solve?
      placeholder: "Example: Add custom CSS support for templates"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        - Add CSS editor in template settings
        - Validate input for security
        - Save to user profile
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Priority Level
      options:
        - Low (nice-to-have)
        - Medium (improves core experience)
        - High (critical functionality)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Mockups, references, or use cases
    validations:
      required: false
