name: Run Prettier

on:
  workflow_dispatch:
  workflow_run:
  workflows: ["CodeQL"]
    types:
      - completed
  push:
    branches: [main, master, test]
  pull_request:
    branches: [main, master, test]

permissions:
  contents: write
  pull-requests: write # Needed to create PRs

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          cache: "pnpm"
          node-version: 22

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm install
      - run: pnpm prettier --write .

      - name: Create branch, commit, and open PR (if changes)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b "prettier-fix-$(date +%s)"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "style: run prettier" && git push origin HEAD && gh pr create --title "Prettier Formatting Fix" --body "Automated Prettier fixes" --head "$(git branch --show-current)" --base main)
        env:
          GH_TOKEN: ${{ github.token }} # GitHub automatically provides this
