name: Run Prettier Fix

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [ main, master, test ]
  pull_request:
    branches: [ main, master, test ]
#  workflow_run:
#    workflows: ["Sync Crowdin Translations"]
#    types:
#      - completed

permissions:
    contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          cache: "pnpm"
          node-version: 22

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install dependencies
        run: pnpm prebuild

      - name: Run Prettier
        run: pnpm prettier --write .

      - name: Commit changes (if any)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "style: run prettier"
          git push