name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ github.token }}
        issue-message: "Thanks for your first issue! 🎉 Don’t worry, we’ll either fix this promptly or pretend it’s a 'feature'—depends on how hard it is to solve. 😉"
        pr-message: "Congratulations on your first PR! 🎉 Welcome to the ‘I now have opinions about code formatting’ club—we’re glad you’re here!"
