name: Publish Docker Image to GHCR

on:
  workflow_run:
    workflows: ["Publish Docker Image to Docker Hub"]
    types:
      - completed

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  IMAGE: pickit420/reactive-resume

permissions:
  packages: write
  contents: read

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.4

      - name: Extract version from package.json
        id: version
        run: echo "version=$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          tags: type=semver,pattern={{version}},prefix=v,value=${{ steps.version.outputs.version }}
          images: |
            ghcr.io/${{ env.IMAGE }}

      - name: Build and Push by Digest
        uses: docker/build-push-action@v5.3.0
        id: build
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=ghcr.io/${{ env.IMAGE }},push-by-digest=true,name-canonical=true,push=true
          build-args: |
            NX_CLOUD_ACCESS_TOKEN=${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: Export Digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload Digest
        uses: actions/upload-artifact@v4.3.3
        with:
          name: digests-${{ matrix.platform }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

      # Add any GHCR-only post-publish steps here
