name: Sync AI Translations

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1 # every Monday at midnight (UTC)

jobs:
  sync-ai-translations:
    if: github.repository == 'lazy-media/Reactive-Resume'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Set up Python (for Whisper)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Whisper and Required Packages
        run: |
          pip install git+https://github.com/openai/whisper.git
          pip install polib

      - name: Run AI Translation Script
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          npx tsx scripts/ai-translate-locales.ts

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B l10n
          git add apps/client/src/locales
          git diff --cached --quiet || git commit -m "AI: Update translations with Whisper"
          git push --force --set-upstream origin l10n

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          branch: l10n
          base: main
          title: "New AI Translations from Whisper"
          body: |
            You've got new translations generated by the local AI tool (OpenAI Whisper) and inserted into the proper message.po files.

            _This pull request was automatically created by the AI Translation workflow._