name: Auto Localize PO Files

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/client/src/locales/**/messages.po'

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install libretranslate
        run: |
          pip install libretranslate

      - name: Start libretranslate server
        run: |
          nohup libretranslate &

      - name: Wait for libretranslate to start
        run: |
          until curl -s http://localhost:5000/health | grep "ok"; do sleep 2; done

      - name: Translate empty msgstr in messages.po files
        env:
          LOCALES_DIR: apps/client/src/locales
        run: |
          import os
          import glob
          import polib
          import requests
          import time
          from pathlib import Path

          def get_language_from_locale(locale):
              # Use first part of xx-YY, or the full code for best match
              return locale

          locales_dir = os.environ['LOCALES_DIR']
          files = glob.glob(f"{locales_dir}/*/messages.po")

          for file_path in files:
              locale = Path(file_path).parent.name
              target_lang = get_language_from_locale(locale)
              po = polib.pofile(file_path)
              changed = False

              for entry in po.untranslated_entries():
                  if entry.msgid.strip() == "":
                      continue
                  # Translate msgid to target language
                  response = requests.post(
                      "http://localhost:5000/translate",
                      json={
                          "q": entry.msgid,
                          "source": "en",
                          "target": target_lang,
                          "format": "text"
                      }
                  )
                  if response.ok:
                      translated = response.json().get("translatedText", "")
                      # Always wrap in quotes and escape as PO requires
                      entry.msgstr = f'"{translated.replace(chr(34), r"\\\"")}"'
                      changed = True
                      time.sleep(0.1)  # Prevent spamming the local server

              if changed:
                  # Use polib to save and keep formatting close to original
                  po.save(file_path)

      - name: Run Prettier on PO files
        run: |
          npm install -g prettier
          prettier --write "apps/client/src/locales/**/*.po"

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create l10n branch, commit changes, and push
        run: |
          git checkout -B l10n
          git add apps/client/src/locales/**/*.po
          git diff --cached --quiet || git commit -m "chore(l10n): auto-fill missing translations in .po files"
          git push -f origin l10n

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: l10n
          base: main
          title: "chore(l10n): Auto-fill missing translations in .po files"
          body: |
            This PR was automatically generated by the localization workflow.
            It fills in empty translations in `messages.po` files using LibreTranslate.
          labels: localization, automated-pr
